// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmdco75P0HZ4hmQsV3lIey5OOWSywvPw',
    appId: '1:1019784451351:web:f6fe0796b7d661d770d352',
    messagingSenderId: '1019784451351',
    projectId: 'receptenapp',
    authDomain: 'receptenapp.firebaseapp.com',
    storageBucket: 'receptenapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2MNy-194jONyaAclMWean5ap3ld7FKQw',
    appId: '1:1019784451351:android:aba1db8c6784a0c470d352',
    messagingSenderId: '1019784451351',
    projectId: 'receptenapp',
    storageBucket: 'receptenapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7C5CBivxgYA4qC-ZJSWAQ2peDMwvyDvA',
    appId: '1:1019784451351:ios:65b1892391099a1c70d352',
    messagingSenderId: '1019784451351',
    projectId: 'receptenapp',
    storageBucket: 'receptenapp.appspot.com',
    iosClientId: '1019784451351-3436qobfr89pmotbf98sd45gp08dpv6g.apps.googleusercontent.com',
    iosBundleId: 'com.vdzon.com',
  );
}
